XCURSOR_THEME=posy-black
XCURSOR_SIZE=24
HYPRCURSOR_SIZE=24
ELECTRON_OZONE_PLATFORM_HINT=auto
GTK_THEME=Graphite-Dark-compact
GDK_BACKEND=wayland,x11
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=gtk3
SDL_VIDEODRIVER=wayland
MOZ_ENABLE_WAYLAND=1
HYPRSHOT_DIR=/home/blox/Pictures/Screenshots
TERMINAL=kitty
