XCURSOR_THEME=Bibata-Modern-Classic
XCURSOR_SIZE=20
HYPRCURSOR_SIZE=20
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
GLOW_STYLE=${XDG_CONFIG_HOME}/glow/blox-theme.json
ELECTRON_OZONE_PLATFORM_HINT=auto
GDK_BACKEND=wayland,x11
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=gtk3
SDL_VIDEODRIVER=wayland
MOZ_ENABLE_WAYLAND=1
HYPRSHOT_DIR=/home/blox/Pictures/Screenshots
TERMINAL=kitty
