$font = MartianMono Nerd Font Propo
$background = rgba(242424cc)
$surface = rgba(1e1e1ee6)
$surface_alt = rgba(3b3c4aff)
$foreground = rgb(cdd6f4)
$muted = rgb(a6adc8)
$red = rgb(f38ba8)
$yellow = rgb(f9e2af)
$blue = rgb(89b4fa)

general {
    hide_cursor = false
    fail_timeout = 5000
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 20
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    color = $background
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 420, 54
    outline_thickness = 1
    rounding = 4

    inner_color = $surface
    outer_color = $surface_alt
    check_color = $blue
    fail_color = $red
    font_color = $foreground
    font_family = $font

    fade_on_empty = false
    placeholder_text = Password
    fail_text = $PAMFAIL
    dots_spacing = 0.28

    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $blue
    font_size = 64
    font_family = $font

    position = 0, -74
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = $muted
    font_size = 18
    font_family = $font

    position = 0, -190
    halign = center
    valign = top
}

label {
    monitor =
    text = 󰒲
    color = $foreground
    font_size = 22
    font_family = $font
    halign = right
    valign = bottom
    position = -126, 30
    onclick = systemctl suspend
}

label {
    monitor =
    text = 
    color = $yellow
    font_size = 22
    font_family = $font
    halign = right
    valign = bottom
    position = -78, 30
    onclick = systemctl reboot
}

label {
    monitor =
    text = ⏻
    color = $red
    font_size = 24
    font_family = $font
    halign = right
    valign = bottom
    position = -30, 28
    onclick = systemctl poweroff
}
