general {
    lock_cmd = ~/.config/quickshell/blox/scripts/power/safe.sh lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 2
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
