splash = false

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/2022-07-07_18.12.55.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/2022-07-07_18.12.55.png
    fit_mode = cover
}