#################
### AUTOSTART ###
#################

# 1. Update systemd environment variables first.
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment SSH_AUTH_SOCK
exec-once = dbus-update-activation-environment --systemd SSH_AUTH_SOCK

# 2. Then start the authentication agent.
exec-once = bash -c "sleep 1 && systemctl --user restart hyprpolkitagent"

# 3. Other apps.
exec-once = quickshell --no-duplicate --path ~/.config/quickshell/blox
exec-once = hyprpaper
exec-once = swaync
exec-once = blueman-applet
exec-once = hypridle
exec-once = systemctl --user restart swayosd
exec-once = hyprsunset
exec-once = vicinae server
exec-once = zen-browser

exec-once = ~/.config/hypr/scripts/code-workspace-router.sh

# Cloud sync is handled by user systemd timers.
