#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GTK_THEME,Adwaita:dark
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = HYPRSHOT_DIR, /home/blox/Pictures/Screenshots

env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
