###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = thunar
#$menu = vicinae toggle
$menu = pgrep -x wofi >/dev/null 2>&1 && killall wofi || wofi --show drun --location top -y 200
$editor = micro
$visual = micro
